"""add method_path col

Revision ID: 2e98ad81d972
Revises: 7556b422a575
Create Date: 2023-09-28 22:50:18.359867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e98ad81d972'
down_revision = '7556b422a575'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timings', sa.Column('method_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timings', 'method_path')
    # ### end Alembic commands ###
