"""add is_fill to Day

Revision ID: 40f4fbfa9118
Revises: d39fb58384eb
Create Date: 2024-02-24 06:50:32.721788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f4fbfa9118'
down_revision = 'd39fb58384eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('is_fill', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('days', 'is_fill')
    # ### end Alembic commands ###
