"""add blacklisted_access_tokens table

Revision ID: 4c75c96fe49f
Revises: 466d8a99e299
Create Date: 2023-09-01 11:26:26.699519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c75c96fe49f'
down_revision = '466d8a99e299'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_access_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    op.create_index('access_token_index', 'blacklisted_access_tokens', ['access_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('access_token_index', table_name='blacklisted_access_tokens')
    op.drop_table('blacklisted_access_tokens')
    # ### end Alembic commands ###
