"""add timings table

Revision ID: 7556b422a575
Revises: 23097bb66e3a
Create Date: 2023-09-28 22:11:53.149233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7556b422a575'
down_revision = '23097bb66e3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('start_ts', sa.DateTime(), nullable=True),
    sa.Column('stop_ts', sa.DateTime(), nullable=True),
    sa.Column('diff_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timings')
    # ### end Alembic commands ###
