"""add timing_stats table

Revision ID: af513b19333e
Revises: 2e98ad81d972
Create Date: 2023-10-02 12:53:08.304936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af513b19333e'
down_revision = '2e98ad81d972'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timing_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('last', sa.Float(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('method_path', sa.String(), nullable=True),
    sa.Column('alert_threshold_ms', sa.Integer(), nullable=True),
    sa.Column('in_alert', sa.Boolean(), nullable=True),
    sa.Column('alert_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timing_stats')
    # ### end Alembic commands ###
